### ISSUE TITLE
Show different form links depending on which year you're viewing

### ISSUE THREAD

**Issue by ErikBoesen** [ErikBoesen/seniormap#39]
@AndrewLester It would be good if the link that's shown for submitting your destination (in the bottom left corner) would change depending on what year is being viewed, i.e. when you switch to 2019 it would be the 2019 form link.

**Comment by ErikBoesen** [comment]
@AndrewLester @TheBlueness We should take a look at actually doing this. I feel like it wouldn't be too hard, right?

**Comment by AndrewLester** [comment]
Definitely not too hard. We can just add the forms to the global sheet.

**Comment by AndrewLester** [comment]
In hindsight, do you think it might be confusing if someone were to click the link to submit (for 2021) after going to view a previous year's map, and ending up at the old submission form? I feel like the only people submitting at the present until next year will be 2021 students anyways. We could indicate the year of the form in the link ("Submit your _2021_ destination here"), but that might go unused.

**Comment by ErikBoesen** [comment]
@AndrewLester I think the year in the link would be clarifying enough.
