### ISSUE TITLE
Trim whitespace on Institution and Name entries

### ISSUE THREAD

**Issue by JonathanOppenheimer** [ErikBoesen/seniormap#65]
This can be done manually on the spreadsheets but I think it'd be cleaner if it could automatically be handled. Whitespace results in issues like having only the white space student submission appear on the map, with the other, nonwhite space student submissions missing. 

Looking at the code it looks like both the institutions and the student names are already trimmed using .trim() but it clearly isn't working properly (and easily demonstratable) as it's happened a couple of times recently and messed up the map.

**Comment by AndrewLester** [comment]
There are other points in the code where trimming is not done, so I think processing it in the sheet would be better as we would have to trim more otherwise.
