### ISSUE TITLE
Class stats tabs counts students that don't appear on the map 

### ISSUE THREAD

**Issue by JonathanOppenheimer** [ErikBoesen/seniormap#66]
Entries on the spreadsheet that don't appear on the map are counted in the statistics -- easily verifiable.

**Comment by AndrewLester** [comment]
I'm not sure if creating a fix for this would make sense since all submissions _should_ appear on the map. If they don't, they give an error in the dev tools console which tells us to fix it. I think I'll close this unless we have further need to fix the issue.

**Comment by JonathanOppenheimer** [comment]
Sometimes they shouldn't be fixed though 😉

Entirely up to you

**Comment by AndrewLester** [comment]
I'm gonna close this in favor of just deleting (or moving) responses that shouldn't go on the map. Or, if they are temporarily hidden, just letting them exist in the count.

EDIT: Because in the end, this isn't exactly about submissions that don't appear. It's about ones that should not...

**Comment by JonathanOppenheimer** [comment]
Fair - the only issue is that if you move/delete the entries that should not appear on the map that are still counted, the student can't revise their response anymore using the form. However, the likelihood that the student revises their (stupid) response using the form is admittedly pretty low.

**Comment by AndrewLester** [comment]
I suggest deleting their response from the form itself if we are to actually remove them. I think this fixes the sheet too perhaps?

**Comment by JonathanOppenheimer** [comment]
Yeah that seems like the best course of action -- fixes the inaccurate count, doesn't screw up the spreadsheet with a resubmission (as what happened with Rohan), and still gives them a chance to submit a valid response. If it's good with you I think we should delete the two most egregious submissions from the form..

**Comment by AndrewLester** [comment]
I agree wholeheartedly; deletion is the necessary next step.
