### ISSUE TITLE
Determine solution for map loading failure

### ISSUE THREAD

**Issue by AndrewLester** [ErikBoesen/seniormap#70]
We need to choose a solution for the issue described in #69. Our options are to either rewrite the code base to use the Google drive API (which may have its own bandwidth/pricing limitations), or we can conduct a test to see if adding `sleep` calls to our code will get around the rate limiting issue.

**Comment by JonathanOppenheimer** [comment]
bro why'd you make an issue that's just saying to solve another issue

**Comment by AndrewLester** [comment]
After testing the sleep solution with @DannyOppenheimer, it appears as though the sleep is still just as inconsistent as without. Moving forward, I think we'll try the Google drive API, but we could also consider better ways to store the data that don't involve Google.
