### ISSUE TITLE
Submit your (year goes here) destination does not change with the displayed map.

### ISSUE THREAD

**Issue by DannyOppenheimer** [ErikBoesen/seniormap#73]
This tab in the bottom left
![image](https://user-images.githubusercontent.com/57159537/129288778-a9aa6eac-4d9e-464e-acb3-b0be046e23d4.png)
only displays the latest year (2021).

In case students what to submit their college location years after their graduation date, the form link and displayed text should change with the selected year seen here:
![image](https://user-images.githubusercontent.com/57159537/129288917-67598a2c-70fc-4ed2-bf21-c4d7412df3e2.png)

**Comment by JonathanOppenheimer** [comment]
This used to be a feature but unfortunately is no longer functional with the papa parse redo.

If I remember correctly, Andrew had set up a modal for the 2019 year explaining the form got deleted and the box in the bottom left just displayed a submission to the most recent year when viewing 2019.

This is kind of non-critical and the old code can also just be deleted if this functionality isn't necessary - the site currently works perfectly with the redo.
