### ISSUE TITLE
Institutions with more than 1 student without a portrait fail to display correct image

### ISSUE THREAD

**Issue by DannyOppenheimer** [ErikBoesen/seniormap#88]
This is an example of the portraits working correctly. When a student doesn't have a picture associated with their name, a default gray dude will be provided:
![image](https://user-images.githubusercontent.com/57159537/207775220-6eb761ef-ca04-45c8-a9af-6b4dad3806c4.png)

When there are 2 or more students without a portrait, the first will receive the default gray guy, and the others will show ugly alt text.
![image](https://user-images.githubusercontent.com/57159537/207775986-f5ca813c-c067-4197-b6f1-43d84097de39.png)

**Comment by AndrewLester** [comment]
Probably need to make these variables `const` or `let`:

https://github.com/apc-mhs/seniormap/blob/e14976d0ce06a9a2dd899c4380cbe617c4582c8c/js/scripts.js#L324-L325

**Comment by DannyOppenheimer** [comment]
Andrew how are you so smart
